city = {
"林祐玄":'WOW　ＧＯＤ' ,
"台北市":'Taipei_City' ,
"基隆市":'Keelung_City',
"新北市":'New_Taipei_City',
"桃園市":'Taoyuan_City',
"新竹市":'Hsinchu_City',
"新竹縣":'Hsinchu_County',
"苗栗縣":'Miaoli_County',
"台中市":'Taichung_City',
"彰化縣":'Changhua_County',
"南投縣":'Nantou_County',
"雲林縣":'Yunlin_County',
"嘉義縣":'Chiayi_County',
"嘉義市":'Chiayi_City',
"宜蘭縣":'Yilan_County',
"花蓮縣":'Hualien_County',
"台東縣":'Taitung_County',
"台南市":'Tainan_City',
"高雄市":'Kaohsiung_City',
"屏東縣":'Pingtung_County',
"連江縣":'Lienchiang_County',
"金門縣":'Kinmen_County',
"澎湖縣":'Penghu_County'
};
module.exports = city;
